### ISSUE TITLE
Stuck at - [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [alisson-anjos/diffusion-pipe-ui-deprecated#1]
Hey thank you for this ui it is going to be a huge help

so I have like 11 images with text captions I setup and upload finalize dataset

then I attempt to train get this

[2024-12-18 17:39:03,064] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)

not sure if I am not waiting long enough but going to give it a few.

with runpod how long should it possible take to start training on it

Sorry noob question just exited for this

**Comment by TheMindExpansionNetwork** [comment]
![image](https://github.com/user-attachments/assets/44064d79-9308-4e14-9f0b-f67badd0bc7c)


Yeah it is weird does not look like pod is cooking at all

**Comment by TheMindExpansionNetwork** [comment]
![image](https://github.com/user-attachments/assets/b828ac66-c52f-4f4b-b367-373807beb152)


just stuck here

**Comment by alisson-anjos** [comment]
@TheMindExpansionNetwork Hello, so I'm trying to make the interface now on top of a fork, I'm trying to set up the docker and make it functional as soon as I finish I'll share the link here, I thought it would be better than creating a separate repository where I need to call the training from a subprocess.

**Comment by slmonker** [comment]
Docker doing the same,
![259eb678-55d2-44d6-a730-88c285c28177](https://github.com/user-attachments/assets/4d27f276-a090-4af1-8371-d56cb3c3d137)

**Comment by TheMindExpansionNetwork** [comment]
> @TheMindExpansionNetwork Hello, so I'm trying to make the interface now on top of a fork, I'm trying to set up the docker and make it functional as soon as I finish I'll share the link here, I thought it would be better than creating a separate repository where I need to call the training from a subprocess.

you are a legend thank you for the help trying to get a flow to work out of my vr headset and stuff this is sweet

**Comment by alisson-anjos** [comment]
> Docker doing the same, ![259eb678-55d2-44d6-a730-88c285c28177](https://private-user-images.githubusercontent.com/184187107/397870856-4d27f276-a090-4af1-8371-d56cb3c3d137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDA2NTcsIm5iZiI6MTczNDgwMDM1NywicGF0aCI6Ii8xODQxODcxMDcvMzk3ODcwODU2LTRkMjdmMjc2LWEwOTAtNGFmMS04MzcxLWQ1NmNiM2MzZDEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNjU5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTA1MmM2MzU3ZDk4NDVkNjNhM2E4MGExMjQxZmE4ZWNmZGNlYzczNWE4ZTkyZGI5NDZjNTYwMDg5NTQ2Njg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZByVZ00LdNmFrLeU9SFJt1mdgdSGdhg70SmaxdSa9AE)

As I told @TheMindExpansionNetwork I'm working on another repository because it's better to integrate with the original project, this repository here has an error :( the log doesn't really appear and that's one of the reasons I forked the original diffusion-pipe repository and I'm working on it, so I don't need to call train.py as a subprocess.

**Comment by alisson-anjos** [comment]
@TheMindExpansionNetwork @slmonker this a new repository https://github.com/alisson-anjos/diffusion-pipe-ui

**Comment by slmonker** [comment]
> @TheMindExpansionNetwork @slmonker this a new repository https://github.com/alisson-anjos/diffusion-pipe-ui

thanks! I will give a shot on this
